import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/AppNavigator';
import { voidTheme } from '../ech0void/theme';

const INTRO_KEY = 'ech0void.intro.accepted.v2';
type Props = NativeStackScreenProps<RootStackParamList, 'Welcome'>;

export default function WelcomeScreen({ navigation }: Props) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    AsyncStorage.getItem(INTRO_KEY).then((accepted) => {
      if (accepted === '1') navigation.replace('Home');
      else setLoading(false);
    }).catch(() => setLoading(false));
  }, [navigation]);

  const enter = async () => {
    await AsyncStorage.setItem(INTRO_KEY, '1');
    navigation.replace('Home');
  };

  if (loading) {
    return <SafeAreaView style={styles.loading}><ActivityIndicator color={voidTheme.cyan} /></SafeAreaView>;
  }

  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.eyebrow}>LOCAL ITC AUDIO INSTRUMENT</Text>
        <Text style={styles.title}>Ech0Void</Text>
        <Text style={styles.tagline}>where echoes become questions</Text>

        <View style={styles.panel}>
          <Text style={styles.panelTitle}>What this actually does</Text>
          <Text style={styles.body}>
            Ech0Void generates its own non-semantic vocal-like fragments, reversed textures, static and scan tones. Device sensors can influence selection and timing. A separate room recording can capture the investigation around it.
          </Text>
        </View>

        <View style={styles.panel}>
          <Text style={styles.panelTitle}>No hidden evidence</Text>
          <Text style={styles.body}>
            Every sound generated by Ech0Void is timestamped in a source ledger. That makes it possible to compare an interesting moment against what the app itself was producing instead of pretending generated audio came from somewhere unknown.
          </Text>
        </View>

        <Text style={styles.disclaimer}>
          Ech0Void is an experimental audio/ITC instrument. Sensor changes, generated fragments, perceived words and recordings do not by themselves establish a paranormal cause. Use headphones when you want the room recording to pick up less of the app's own speaker output.
        </Text>

        <Pressable accessibilityRole="button" onPress={enter} style={styles.enter}>
          <Text style={styles.enterText}>ENTER ECH0VOID</Text>
        </Pressable>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: voidTheme.bg },
  loading: { flex: 1, backgroundColor: voidTheme.bg, alignItems: 'center', justifyContent: 'center' },
  content: { padding: 24, paddingTop: 54, paddingBottom: 42 },
  eyebrow: { color: voidTheme.cyan, letterSpacing: 3, fontSize: 11, fontWeight: '800' },
  title: { color: voidTheme.text, fontSize: 54, fontWeight: '900', letterSpacing: -2, marginTop: 7 },
  tagline: { color: voidTheme.violet, fontSize: 15, letterSpacing: 1.2, marginBottom: 28 },
  panel: { backgroundColor: voidTheme.panel, borderColor: voidTheme.border, borderWidth: 1, borderRadius: 18, padding: 18, marginBottom: 14 },
  panelTitle: { color: voidTheme.text, fontSize: 17, fontWeight: '800', marginBottom: 8 },
  body: { color: voidTheme.muted, lineHeight: 21, fontSize: 14 },
  disclaimer: { color: voidTheme.muted, fontSize: 12, lineHeight: 18, marginTop: 4, marginBottom: 24 },
  enter: { backgroundColor: voidTheme.cyan, borderRadius: 16, paddingVertical: 17, alignItems: 'center' },
  enterText: { color: '#021014', fontWeight: '900', letterSpacing: 1.5 },
});
