plugins {
    id 'com.android.application'
}

android {
    namespace 'app.echovoid.nativev3'
    compileSdk 35

    defaultConfig {
        applicationId 'app.echovoid.nativev3'
        minSdk 24
        targetSdk 35
        versionCode 400
        versionName '4.0.0-hsb-core-alpha'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix ''
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
